var map = L.map('map').setView([42.87093, 74.60335], 13);
var count = 1;
//'http://{s}.tile.cloudmade.com/3a5a93b0788845f59038e598884ecdad/92017/256/{z}/{x}/{y}.png'
L.tileLayer("map/map/{s}/{z}/{x}/{y}.png", {
	maxZoom: 18,
	attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://cloudmade.com">CloudMade</a>'
}).addTo(map);
/*var cloudmadeUrl = 'http://{s}.mqcdn.com/tiles/1.0.0/osm/{z}/{x}/{y}.jpg';
var subDomains = ['otile1','otile2','otile3','otile4'];
var cloudmadeAttrib = 'Data, imagery and map information provided by <a href="http://open.mapquest.co.uk" target="_blank">MapQuest</a>, <a href="http://www.openstreetmap.org/" target="_blank">OpenStreetMap</a> and contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/" target="_blank">CC-BY-SA</a>';
var cloudmade = new L.TileLayer(cloudmadeUrl, {maxZoom: 18, attribution: cloudmadeAttrib, subdomains: subDomains});

var bishkek = new L.LatLng(42.87093, 74.60335);

var map = new L.Map('map', {center: bishkek, zoom: 13, layers : [cloudmade]});
*/
var myMarkers = new Array();

popup = L.popup();

var click_cheker = 0;

var httpGet = function(theUrl) {
		var xmlHttp;
		xmlHttp = null;
		xmlHttp = new XMLHttpRequest();
		xmlHttp.open("GET", theUrl, false);
		xmlHttp.send(null);
		return xmlHttp.responseText;
	};

// Generated by CoffeeScript 1.7.1
var update_news = (function() {
	var i, jsonArr, url, _i, _len;

	url = "Controller/Crime_controller";

	jsonArr = JSON.parse(httpGet(url));

	var feed = document.getElementById("feedForm");
	var for_feed = "";
	var for_temp = "";
	for (_i = 0, _len = jsonArr.length; _i < _len; _i++)
	{
		i = jsonArr[_i];
		for_feed += '<br>';
		for_feed += '<div class="titleContainer">' + i['category'];
		for_feed += '<div class="titleTime">' + i['time'] + '</div>';
		for_feed += '</div>';
		for_feed += '<div class="newsItem">';
		for_feed += '<br>';
		for_feed += i['description']
		for_feed += '<br><br>'// + i['place']
		for_feed += i['date']
		for_feed += '</div>';
		
		for_feed += for_temp;
		for_temp = for_feed;
		for_feed = "";
		var temp = i['description'];
		temp = temp.split(" ");
		
		if(temp.length >=3){
			var popup_message = '<b>'+i['category']+'</b><br />'+temp[0]+" "+temp[1]+" "+temp[2]+'<br />'+'<a onclick=comma("'+i['crime_id']+'")>Читать дальше →</a>';
		}
		else{
			var popup_message = '<b>'+i['category']+'</b><br />'+temp[0]+'<br />'+'<a onclick=comma("'+i['crime_id']+'")>Читать дальше →</a>';
		}
		marker = L.marker([i['latitude'], i['longitude']]).addTo(map)
			.bindPopup(popup_message);
		myMarkers.push(marker);
	}
	feed.innerHTML=for_temp;

});
/*CoffeeScript end*/

update_news();

//var k_lng = document.getElementById('longitude')
//var k_lat = document.getElementById('latitude')

function onMapClick(e)
{
	if (click_cheker === 1)
	{

		var lat = (e.latlng.lat);
		var lng = (e.latlng.lng);
		document.getElementById('latitude').value = lat;
		document.getElementById('longitude').value = lng;
	/*	if (count === 1)
		{
			marker = new L.marker(e.latlng, {id:1}).addTo(map)
				.bindPopup("<b>Это произошло</b><br />здесь.").openPopup();
			count+=1;
		} 
		else
		{*/
			var newLatLng = new L.LatLng(lat, lng);
			marker.setLatLng(newLatLng).addTo(map)
				.bindPopup("<b>Choose</b><br />placse on map.<br><button class=\"btn btn-primary\" data-target=\"#myModal\" data-toggle=\"modal\" type=\"button\">Сообщить!</button>").openPopup();
		//};
		//myMarkers .push(marker);
	};
};

function submit ()
{
	vex.defaultOptions.className = 'vex-theme-flat-attack';
	vex.dialog.buttons.YES.text = "Сообщить!";
	vex.dialog.buttons.NO.text = "Отмена";
	var todayDateString;

	todayDateString = new Date().toJSON().slice(0, 10);

	vex.dialog.open(
	{
		message: 'Пожалуйста, опишите преступление',
		input: "<style>\n    .vex-custom-field-wrapper {\n        margin: 1em 0;\n    }\n    .vex-custom-field-wrapper > label {\n        display: inline-block;\n        margin-bottom: .2em;\n    }\n</style>\n <div class=\"vex-custom-field-wrapper\">\n    <label for=\"category\">Категория</label>\n <div class=\"vex-custom-input-wrapper\">\n <input name=\"category\" type=\"text\" placeholder=\"Категория\" required />\n <div class=\"vex-custom-field-wrapper\">\n    <label for=\"address\">Адрес</label>\n <div class=\"vex-custom-input-wrapper\">\n <input name=\"address\" type=\"text\" placeholder=\"Адрес\" required />\n <div class=\"vex-custom-field-wrapper\">\n    <label for=\"comment\">Комментарий</label>\n <div class=\"vex-custom-input-wrapper\">\n <input name=\"comment\" type=\"text\" placeholder=\"Комментарий\" required /> <div class=\"vex-custom-field-wrapper\">\n    <label for=\"date\">Дата</label>\n    <div class=\"vex-custom-input-wrapper\">\n        <input name=\"date\" type=\"date\" value=\"" + todayDateString + "\" />\n  </div>\n</div>",
		callback: function(data)
		{
			if (data === false) 
			{
			  return console.log('Cancelled');
			}
			console.log('Date', data.date);
			return $('.demo-result-custom-vex-dialog').show().html("<h4>Result</h4>\n<p>\n    Date: <b>" + data.date + "</b><br/>\n");
		}
	});
};
map.on('click', onMapClick);